[package]
name = "killallgit-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "killallgit"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
dialoguer = { version = "0.11", features = ["fuzzy-select"] }
anyhow = "1.0"
regex = "1"
